apiVersion: v1
kind: Service
metadata:
  name: {{ include "theia.fullname" . }}
  labels:
    {{- include "theia.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3000
  selector:
    {{- include "theia.selectorLabels" . | nindent 4 }}